create select
peaksoft-school/air-bnb-js9 pull request #11
Opened 2023-07-10 10:38 UTC by emirduishonaliev

2023-07-10 13:16 UTC, kursanovN approved these changes

2023-07-10 14:13 UTC, Gulzat5 approved these changes

2023-07-10 14:17 UTC, barsuser04 approved these changes

2023-07-11 06:03 UTC, AziatAbd requested changes

2023-07-11 06:03 UTC, AziatAbd commented on src/components/UI/select/Select.jsx
> +      <div>
уберите div

2023-07-11 06:03 UTC, AziatAbd commented on src/components/UI/select/Select.jsx
> +               <MenuItem value="">All</MenuItem>
если выбрать All, то он должен возвращать все id внутри data, а не пустое value

2023-07-11 06:41 UTC, merged