Feature/header footer
peaksoft-school/air-bnb-js9 pull request #12
Opened 2023-07-10 14:14 UTC by barsuser04

2023-07-10 14:19 UTC, kursanovN approved these changes

2023-07-10 14:21 UTC, FrontAziret26 approved these changes

2023-07-10 14:39 UTC, Gulzat5 approved these changes

2023-07-11 05:39 UTC, AziatAbd requested changes

2023-07-11 05:39 UTC, AziatAbd commented on src/layout/Header/Header.jsx
> +            </SearchDiv>
так не пойдёт, загуглите mui search input

2023-07-11 05:39 UTC, AziatAbd commented on src/layout/Header/Header.jsx
> +   marginTop: '50px',
это тоже не нужно, уберите

2023-07-11 06:48 UTC, AziatAbd requested changes

2023-07-11 06:48 UTC, AziatAbd commented on src/App.js
> +      </div>
Апп тазалап койсонуз

2023-07-11 06:50 UTC, merged