theme-setup finish
peaksoft-school/air-bnb-js9 pull request #2
Opened 2023-07-07 12:30 UTC by FrontAziret26

2023-07-07 13:23 UTC, barsuser04 approved these changes

2023-07-07 13:26 UTC, emirduishonaliev approved these changes

2023-07-07 14:43 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/541493b6-41c9-49c3-b17a-a27ca6ded378)
development'ке push кылыш керек

2023-07-07 14:45 UTC, AziatAbd requested changes

2023-07-07 14:45 UTC, AziatAbd commented on package.json
> +    "styled-components": "^5.3.11",
кереги жок

2023-07-07 14:45 UTC, AziatAbd commented on .eslintrc.json
> +      "import/no-extraneous-dependencies": "off",
из-за чего это добавили?

2023-07-08 10:30 UTC, FrontAziret26 commented
пт, 7 июл. 2023 г. в 20:45, Aziat ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In package.json
> <https://github.com/peaksoft-school/air-bnb-js9/pull/2#discussion_r1255935982>
> :
>
> >      ***@***.***/jest-dom": "^5.16.5",
>      ***@***.***/react": "^13.4.0",
>      ***@***.***/user-event": "^13.5.0",
>      "react": "^18.2.0",
>      "react-dom": "^18.2.0",
>      "react-scripts": "5.0.1",
> +    "styled-components": "^5.3.11",
>
> кереги жок
> ------------------------------
>
> In .eslintrc.json
> <https://github.com/peaksoft-school/air-bnb-js9/pull/2#discussion_r1255937438>
> :
>
> > @@ -23,6 +23,7 @@
>        "react-hooks/exhaustive-deps": "off",
>        "react-hooks/rules-of-hooks": "error",
>        "react/function-component-definition": "off",
> +      "import/no-extraneous-dependencies": "off",
>
> из-за чего это добавили?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/peaksoft-school/air-bnb-js9/pull/2#pullrequestreview-1519084282>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXHOQ3XR5PRC6MYPQNF7KR3XPAOH5ANCNFSM6AAAAAA2BYCUVQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-08 10:31 UTC, FrontAziret26 commented
Ондодум !


сб, 8 июл. 2023 г. в 16:30, Азирет Тойчубеков <
***@***.***>:

>
>
> пт, 7 июл. 2023 г. в 20:45, Aziat ***@***.***>:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In package.json
>> <https://github.com/peaksoft-school/air-bnb-js9/pull/2#discussion_r1255935982>
>> :
>>
>> >      ***@***.***/jest-dom": "^5.16.5",
>>      ***@***.***/react": "^13.4.0",
>>      ***@***.***/user-event": "^13.5.0",
>>      "react": "^18.2.0",
>>      "react-dom": "^18.2.0",
>>      "react-scripts": "5.0.1",
>> +    "styled-components": "^5.3.11",
>>
>> кереги жок
>> ------------------------------
>>
>> In .eslintrc.json
>> <https://github.com/peaksoft-school/air-bnb-js9/pull/2#discussion_r1255937438>
>> :
>>
>> > @@ -23,6 +23,7 @@
>>        "react-hooks/exhaustive-deps": "off",
>>        "react-hooks/rules-of-hooks": "error",
>>        "react/function-component-definition": "off",
>> +      "import/no-extraneous-dependencies": "off",
>>
>> из-за чего это добавили?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/peaksoft-school/air-bnb-js9/pull/2#pullrequestreview-1519084282>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXHOQ3XR5PRC6MYPQNF7KR3XPAOH5ANCNFSM6AAAAAA2BYCUVQ>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-07-08 11:40 UTC, closed without merging