Feature/feedback
peaksoft-school/air-bnb-js9 pull request #22
Opened 2023-07-13 13:57 UTC by emirduishonaliev

2023-07-13 19:14 UTC, FrontAziret26 approved these changes

2023-07-14 04:46 UTC, kursanovN approved these changes

2023-07-14 09:43 UTC, AziatAbd commented
фото, кол-во звёзд, кол-во лайков, кол-во дизлайков, дата должны приходит через пропс

2023-07-14 09:45 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/8177a87c-5fb1-4c44-a81d-7324513b1269)
если текст большой то должна появиться текст ' see more ' как здесь:
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/2d6e0963-3111-4568-bf58-f02250f2fae0)
после того как нажал на ' see more ' вместо него появиться текст ' see less ' если на него нажать то текст должен уменьшиться

2023-07-14 09:51 UTC, AziatAbd requested changes

2023-07-14 09:51 UTC, AziatAbd commented on src/components/UI/feedback/Feedback.jsx
> +   margin: '0 auto ',
уберите margin

2023-07-14 09:51 UTC, AziatAbd commented on src/components/UI/feedback/Feedback.jsx
> +         </GradeBlock>
сделайте так чтобы можно было на них нажимать, вместо div используйте iconButton

2023-07-14 09:51 UTC, AziatAbd commented on src/components/UI/feedback/Feedback.jsx
> +                     />
он должен только отображать сколько звёзд есть и всё

2023-07-15 09:53 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/0e5a43fb-0d31-40bb-9e1e-2b2e098d112d)
meatballs должна появиться как модалка поверх компонентов чтобы он не разрушал дизайн

2023-07-15 09:58 UTC, AziatAbd requested changes

2023-07-15 09:58 UTC, AziatAbd commented on src/components/UI/rating/RatingStars.jsx
> +            <Rating name="simple-controlled" value={starRating} />
добавьте readOnly

2023-07-15 09:58 UTC, AziatAbd commented on src/components/UI/feedback/Feedback.jsx
> +               </a>
просто span а не ' a ' тег

2023-07-15 09:59 UTC, AziatAbd commented
и ещё через пропс должны приходить функции для лайк и диззлайк

2023-07-17 03:07 UTC, merged