Feature/cards
peaksoft-school/air-bnb-js9 pull request #23
Opened 2023-07-14 04:50 UTC by Gulzat5

2023-07-14 05:47 UTC, emirduishonaliev approved these changes

2023-07-14 13:10 UTC, barsuser04 approved these changes

2023-07-15 09:29 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/2d50faba-beff-4325-812d-8e1f523b1a36)
они должны быть одинаково размера. стрелки должны появиться при hover'е

2023-07-15 09:31 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/c4fb32fe-b0ca-45c9-8518-9af004fb5e71)
если текст длинный то должны появиться три точки как здесь

2023-07-15 09:42 UTC, AziatAbd requested changes

2023-07-15 09:42 UTC, AziatAbd commented on src/components/UI/cards/Cards.jsx
> +const data = [
добавьте этот массив в general и оттуда импортируйте её

2023-07-15 09:42 UTC, AziatAbd commented on src/components/UI/cards/Cards.jsx
> +export function Cards() {
через пропс должны прийти массив с данными, функции для кнопок и тд

2023-07-20 12:35 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/dfae6db9-eeee-45e2-96b7-2e33c823e34f)


**если нету button'a то там должен быть meatballs, как здесь**

![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/12cf2acf-3a89-4b9d-b933-480914ab312b)

2023-07-24 07:42 UTC, merged