Feature/house detail page
peaksoft-school/air-bnb-js9 pull request #27
Opened 2023-07-16 17:28 UTC by kursanovN

2023-07-17 06:18 UTC, barsuser04 approved these changes

2023-07-17 06:20 UTC, barsuser04 approved these changes

2023-07-17 07:08 UTC, AziatAbd requested changes

2023-07-17 07:08 UTC, AziatAbd commented on src/components/UI/house-detail/HouseDetail.jsx
> +export function HouseDetail() {
через пропс должны приходить массив с данными

2023-07-17 07:08 UTC, AziatAbd commented on src/components/UI/house-detail/HouseDeteilData.js
> +]
откройте это в general

2023-07-17 07:08 UTC, AziatAbd commented on src/components/UI/house-detail/HouseDetail.jsx
> +      </Container>
сделайте это с помощью слайдера, чтобы можно было переключать картинки

2023-07-20 03:19 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/b804c042-1d39-444f-9488-6dcebb051de3)
уберите это

2023-07-20 03:20 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/eade024d-ca28-4e4b-98c6-561dc02aa6e1)
размер немножко поменьше сделайте

2023-07-20 03:20 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/958e3d46-5e68-4161-80a2-ab4927f70a3a)
а их чуть больше

2023-07-20 06:56 UTC, AziatAbd requested changes

2023-07-20 06:56 UTC, AziatAbd commented on package.json
> +=======
исправьте это

2023-07-20 08:16 UTC, merged