finish leave-feeedback
peaksoft-school/air-bnb-js9 pull request #36
Opened 2023-07-25 12:13 UTC by barsuser04

2023-07-25 12:18 UTC, Gulzat5 approved these changes

2023-07-25 12:25 UTC, kursanovN approved these changes

2023-07-25 13:09 UTC, AziatAbd requested changes

2023-07-25 13:09 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +               <StyledAhref href="!#">Add photos to the review</StyledAhref>
зачем ' a ' тег? Просто сделай так, чтобы при нажатии на неё, я мог загрузить фото

2023-07-25 13:09 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +      <Container onSubmit={submitHandler}>
это ещё модалкой должна быть

2023-07-25 13:09 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +export function LeaveFeedback() {
функции для открытие, закрытия модалки, функция для которая собирает данные отзыва тоже должны приходить через пропсы

2023-07-25 13:09 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +   }
в бэк отправите только текст и всё? Добавьте рейтинги, фото

2023-07-25 13:11 UTC, AziatAbd requested changes

2023-07-25 13:11 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +}))
коды повторяются

2023-07-26 11:48 UTC, AziatAbd requested changes

2023-07-26 11:48 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +      </div>
удалите, оставьте только модалку

2023-07-26 11:48 UTC, AziatAbd commented on src/components/leave-feedback/LeaveFeeadback.jsx
> +   const [openModal, setOpenModal] = useState(false)
open modal из пропса должен прийти

2023-07-27 04:10 UTC, AziatAbd approved these changes

2023-07-27 04:10 UTC, merged