create payment
peaksoft-school/air-bnb-js9 pull request #39
Opened 2023-07-27 12:41 UTC by kursanovN

2023-07-31 12:17 UTC, emirduishonaliev approved these changes

2023-07-31 12:17 UTC, barsuser04 approved these changes

2023-08-01 07:19 UTC, AziatAbd requested changes

2023-08-01 07:19 UTC, AziatAbd commented on src/components/payment/PaymenrInDarePicker.jsx
> +            change the date
а чё тексты одинаковые?

2023-08-01 07:19 UTC, AziatAbd commented on src/components/payment/ResultPaymentForm.jsx
> +            change the date
тоже самое

2023-08-01 07:19 UTC, AziatAbd commented on src/components/payment/ResultPaymentForm.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
удали это

2023-08-01 07:19 UTC, AziatAbd commented on src/components/payment/ResultPaiment.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
и это

2023-08-01 07:19 UTC, AziatAbd commented on src/components/payment/ResultPaymentForm.jsx
> +         console.error('Ошибка при получении токена:', error)
откройте какой-нибудь state и дайте error туда

2023-08-01 07:19 UTC, AziatAbd commented on src/components/payment/ResultPaymentForm.jsx
> +         console.log('Токен карты:', token)
он должен вернуть не только токен а ещё и время

2023-08-01 11:19 UTC, merged