Feature/snackbar
peaksoft-school/air-bnb-js9 pull request #4
Opened 2023-07-08 06:31 UTC by kursanovN

2023-07-08 06:32 UTC, emirduishonaliev approved these changes

2023-07-08 08:44 UTC, FrontAziret26 approved these changes

2023-07-08 08:44 UTC, FrontAziret26 commented on package.json
> +    "@emotion/styled": "^11.11.0",
Styled component ти колдонбо!

2023-07-08 08:44 UTC, FrontAziret26 commented on src/components/UI/snackbar/Snackbar.jsx
> +const Toast = styled.div`
MUI дын style нын колдон

2023-07-08 09:26 UTC, emirduishonaliev approved these changes

2023-07-08 09:36 UTC, AziatAbd requested changes

2023-07-08 09:36 UTC, AziatAbd commented on src/App.js
> +         <Snackbar />
App очистить

2023-07-08 09:36 UTC, AziatAbd commented on src/components/UI/snackbar/Snackbar.jsx
> +                  {/* Бул жакка children келет */}
children келсе children беринда

2023-07-08 09:36 UTC, AziatAbd commented on src/components/UI/snackbar/Snackbar.jsx
> +                  {/* Бул жакка children келет */}
тоже самое

2023-07-08 09:36 UTC, AziatAbd commented on src/components/UI/snackbar/Snackbar.jsx
> +         </button>
зачем Button здесь?

2023-07-08 09:36 UTC, AziatAbd commented on src/components/UI/snackbar/Snackbar.jsx
> +         )}
одного хватит

2023-07-08 09:41 UTC, AziatAbd commented
Функцияны эле чыкырганга Snackbar иштеш керек. Зачес кнопка ичинде? Сделайте reusable snackbar

2023-07-10 02:41 UTC, Kamchybekk commented
еще update менен болсун.Например loading toastify ды либло sucess либо error айлангандай болуш керек.

2023-07-10 07:10 UTC, closed without merging