Feature/table
peaksoft-school/air-bnb-js9 pull request #43
Opened 2023-08-07 07:01 UTC by Gulzat5

2023-08-07 07:36 UTC, FrontAziret26 approved these changes

2023-08-07 07:36 UTC, emirduishonaliev approved these changes

2023-08-08 11:15 UTC, AziatAbd commented
когда удаляю одного пользователя, он исчезает только после перезагрузки страницы

2023-08-08 11:17 UTC, AziatAbd commented
добавьте ещё модалку, когда нажимаю на кнопку удаления, чтобы он спрашивал точно хочу ли я удалить

2023-08-09 08:39 UTC, AziatAbd requested changes

2023-08-09 08:39 UTC, AziatAbd commented on src/components/table/Table.jsx
> +         console.log('error: ', error)
удалите console.log и добавьте snackbar, когда запрос успешно выполнен и когда выходит ошибка

2023-08-09 08:39 UTC, AziatAbd commented on src/components/table/Table.jsx
> +                              )}
вызовите модалку снаружи, а не внутри

2023-08-09 12:02 UTC, AziatAbd approved these changes

2023-08-09 12:02 UTC, merged