Feature/anouncement
peaksoft-school/air-bnb-js9 pull request #45
Opened 2023-08-14 06:14 UTC by emirduishonaliev

2023-08-14 07:11 UTC, AziatAbd requested changes

2023-08-14 07:11 UTC, AziatAbd commented on src/components/anouncement/Anouncement.jsx
>     const schema = yup.object().shape({
const schema можно в helpers или general переместить

2023-08-14 07:11 UTC, AziatAbd commented on src/components/anouncement/Anouncement.jsx
>     }
отдельный dispatch можно и не открывать, сделайте локальный запрос

2023-08-14 07:12 UTC, AziatAbd requested changes

2023-08-14 07:12 UTC, AziatAbd commented on src/components/anouncement/Anouncement.jsx
>        console.log(data, 'data')
console.log удаляем

2023-08-14 07:13 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/c6558be9-7f99-468c-aa7e-00ad9d53612c)
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/b429b06b-9e85-4031-a136-fdadf2088310)
смотрите какие ключи берут бэк и какие ключи отправляете вы

2023-08-14 07:14 UTC, AziatAbd commented
добавьте snackbar'ы, соедините роуты, сделайте navigate после успешного добавления

2023-08-14 07:15 UTC, AziatAbd commented
верните AppRoutes в App.js

2023-08-17 10:04 UTC, AziatAbd requested changes

2023-08-17 10:04 UTC, AziatAbd commented on src/api/postImageAxiosInstance.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTIyNTE5NzQsImlhdCI6MTY5MTk5Mjc3NCwidXNlcm5hbWUiOiJhbGlzdGVyQGdtYWlsLmNvbSJ9.KngtGF5uVaZPyBRboLhGYUf1rQggPlyKfGHaaG0-XYE'
удалите

2023-08-17 10:04 UTC, AziatAbd commented on src/components/anouncement/Anouncement.jsx
> +   }
фотки не отправляются?

2023-08-17 10:04 UTC, AziatAbd commented
роуты тоже соедините

2023-08-22 05:01 UTC, kursanovN approved these changes

2023-08-22 06:28 UTC, merged