admin-userPage-intyegration
peaksoft-school/air-bnb-js9 pull request #46
Opened 2023-08-15 04:53 UTC by barsuser04

2023-08-17 12:58 UTC, Gulzat5 approved these changes

2023-08-18 10:38 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/6deb22da-f969-48df-a2f7-47824f51ee5d)
сизде block, delete деген эле болот

2023-08-18 10:47 UTC, AziatAbd requested changes

2023-08-18 10:47 UTC, AziatAbd commented on src/components/tabs/Bookings.jsx
> +         <h1>Bookings</h1>
неге пустой?

2023-08-18 10:47 UTC, AziatAbd commented on src/components/tabs/MyAnnouncement.jsx
> +         />
если массив пустой болсо бир текст чыгарып коюн, чтобы пустой болуп турбаш учун

2023-08-18 10:48 UTC, AziatAbd commented
сизде полностью страницага cursor: pointer берилгенби?

2023-08-21 03:28 UTC, merged