Feature/applications
peaksoft-school/air-bnb-js9 pull request #47
Opened 2023-08-20 18:27 UTC by kursanovN

2023-08-21 05:15 UTC, emirduishonaliev approved these changes

2023-08-21 05:28 UTC, barsuser04 approved these changes

2023-08-22 04:49 UTC, AziatAbd commented
добавьте snackbar'ы

2023-08-22 04:50 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/a13c026c-5b81-4c71-b960-8ff7c1d07ae0)
meatballs всегда открывается с краю, даже если нажимаю в середине

2023-08-22 04:51 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/63fbe6fd-0cf2-4221-b210-bd86c58da41e)
сделайте ровнее, а то 6 сверху и 4 снизу

2023-08-22 04:55 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/d1492138-56a0-4ac0-a9cd-6d297a342533)
куда уплыл log out?

2023-08-22 04:57 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/bd5f8b72-1ae4-4192-ba2e-dd30657f5196)
цвет не доходит до конца

2023-08-22 05:03 UTC, AziatAbd commented
app.js AppRoutes дегенди чыкырып коюнуз

2023-08-23 06:07 UTC, AziatAbd requested changes

2023-08-23 06:07 UTC, AziatAbd commented on src/store/Index.js
> +})
authSlice каякта?

2023-08-24 04:27 UTC, AziatAbd requested changes

2023-08-24 04:27 UTC, AziatAbd commented on src/store/admin-application/ApplicationThunk.js
> +)
delete, accept, reject болгондо get запросторду чыкырып коюн

2023-08-24 04:27 UTC, AziatAbd commented on src/store/admin-application/ApplicationThunk.js
> +)
а то перезагрузка болгондон кийин иштейт экен

2023-08-24 04:27 UTC, AziatAbd commented on src/routes/AppRoutes.jsx
> +               path="application/"
"/" очуруп коюн application озу эле болсун

2023-08-24 06:42 UTC, AziatAbd approved these changes

2023-08-24 06:42 UTC, merged