Feature/announcements get all
peaksoft-school/air-bnb-js9 pull request #55
Opened 2023-08-29 12:42 UTC by FrontAziret26

2023-09-03 16:20 UTC, kursanovN approved these changes

2023-09-04 05:02 UTC, barsuser04 approved these changes

2023-09-04 10:23 UTC, Kamchybekk commented on src/components/main/MainPage.jsx
>     const [userLogin, setUserLogin] = useState(false)
delete console.log

2023-09-13 09:36 UTC, emirduishonaliev approved these changes

2023-09-14 04:59 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/78186e8c-2ede-47e7-a393-226b2d1b3928)
если нажимаю цвет не меняется

2023-09-14 05:00 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/24a5d79a-fc36-44d8-b6fe-83771e5afb7e)
как я узнаю что он добавился в избранные, если при повторном нажатии один и тот же текст

2023-09-14 05:00 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/9c29920c-d67a-4f70-b241-46f197b2501a)
что с селектами?

2023-09-14 05:03 UTC, AziatAbd commented
пагинация не работает

2023-09-14 05:08 UTC, AziatAbd requested changes

2023-09-14 05:08 UTC, AziatAbd commented on src/api/cardService.js
> +   console.log(params, 'params')
удаляем консоль

2023-09-14 05:08 UTC, AziatAbd commented on src/config/axiosInstance.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTQ3NjYyOTEsImlhdCI6MTY5NDUwNzA5MSwidXNlcm5hbWUiOiJhbGlzdGVyQGdtYWlsLmNvbSJ9.Duu10-yfW_hZK74_REABhib5NDheOPP67HGy4MRTXd8'
зачем токен ручной берип?

2023-09-16 09:40 UTC, merged