Feature/get cards byid
peaksoft-school/air-bnb-js9 pull request #58
Opened 2023-09-06 09:47 UTC by barsuser04

2023-09-12 19:08 UTC, kursanovN approved these changes

2023-09-12 23:19 UTC, Gulzat5 approved these changes

2023-09-13 05:10 UTC, emirduishonaliev approved these changes

2023-09-13 05:14 UTC, kursanovN reviewed
конфликт чеч

2023-09-14 04:49 UTC, AziatAbd requested changes

2023-09-14 04:49 UTC, AziatAbd commented on src/components/UI/feedback/Feedback.jsx
> +   console.log(data)
удаляем консоль

2023-09-14 04:49 UTC, AziatAbd commented on src/components/UI/feedback/Feedback.jsx
>           console.error(error)
здесь тоже

2023-09-14 04:49 UTC, AziatAbd commented on src/components/UI/name-hotel/NameOfHotel.jsx
> +         console.log('error: ', error)
используйте toast

2023-09-14 04:49 UTC, AziatAbd commented on src/pages/AnnouncementDetailPage.jsx
> +/* eslint-disable import/no-unresolved */
зачем оффаете?

2023-09-14 04:49 UTC, AziatAbd commented on src/pages/AnnouncementDetailPage.jsx
> +   }, [dispatch])
в одном useEffect'e один dispatch должен быть

2023-09-14 04:49 UTC, AziatAbd commented on src/routes/AppRoutes.jsx
> +   const [stat, setStat] = useState('')
для чего этот stat? пишите логические имена

2023-09-14 04:49 UTC, AziatAbd commented on src/store/getAnnouncement/GetAnnouncementByIdThunk.js
> +// )
весь не нужный код удалите

2023-09-14 04:49 UTC, AziatAbd commented on src/store/index.js
>        [ModalSlice.name]: ModalSlice.reducer,
не пишите имя файла с большой буквой. Только компоненты должны быть большими

2023-09-14 04:50 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/026f4010-bf16-44c6-8179-10d4f815820c)
где внутренняя страница?

2023-09-15 03:54 UTC, merged