Feature/button
peaksoft-school/air-bnb-js9 pull request #6
Opened 2023-07-08 07:25 UTC by Gulzat5

2023-07-08 07:56 UTC, FrontAziret26 approved these changes

2023-07-08 09:26 UTC, emirduishonaliev approved these changes

2023-07-10 10:08 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +            width: `${props.width || '196px'}`,
фиксированный размер не нужен

2023-07-10 10:11 UTC, AziatAbd requested changes

2023-07-10 10:11 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +            width: `${props.width || '24.5%'}`,
фиксированный размер не нужен

2023-07-10 10:11 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +            padding: '10px 158px',
уменьшите padding, не нужно так делать

2023-07-10 10:11 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/8acb4967-af68-414d-854d-bd093663d759)

2023-07-10 10:12 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js9/assets/115453436/675b69f9-9ae7-4b23-bdec-f87b6f5233ac)
conflicts!

2023-07-10 12:17 UTC, AziatAbd requested changes

2023-07-10 12:17 UTC, AziatAbd commented on src/App.js
> +         </Button>
Очистить App.js

2023-07-10 12:17 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +            width: `${props.width}`,
width и props вообще не нужны

2023-07-11 05:49 UTC, merged